# Generated by Django 4.2.30 on 2026-09-14 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('product_name', models.CharField(help_text='Name of the product or service', max_length=200)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Home Appliance', 'Home Appliance'), ('Mobile & Computers', 'Mobile & Computers'), ('Fashion & Clothing', 'Fashion & Clothing'), ('Food & Beverages', 'Food & Beverages'), ('Furniture', 'Furniture'), ('Internet & Telecom', 'Internet & Telecom'), ('Delivery & Logistics', 'Delivery & Logistics'), ('Repair & Maintenance', 'Repair & Maintenance'), ('Travel & Transport', 'Travel & Transport'), ('Financial & Billing', 'Financial & Billing'), ('Other', 'Other Services')], default='Electronics', max_length=50)),
                ('seller', models.CharField(help_text='Seller, Manufacturer, or Service Provider', max_length=200)),
                ('purchase_date', models.DateField(help_text='Date of purchase or service agreement')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Total amount paid (in ₹)', max_digits=12)),
                ('complaint_type', models.CharField(choices=[('Defective Product', 'Defective Product'), ('Damaged Product', 'Damaged Product'), ('Wrong Product', 'Wrong Product'), ('Product Not Delivered', 'Product Not Delivered'), ('Late Delivery', 'Late Delivery'), ('Poor Quality', 'Poor Quality'), ('Overcharging', 'Overcharging'), ('Refund Issue', 'Refund Issue'), ('Warranty Issue', 'Warranty Issue'), ('Misleading Information', 'Misleading Information'), ('Service Issue', 'Service Issue'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the grievance')),
                ('expected_resolution', models.CharField(choices=[('Refund', 'Full / Partial Refund'), ('Replacement', 'Product Replacement'), ('Repair', 'Free Repair Service'), ('Delivery', 'Immediate Delivery / Dispatch'), ('Warranty Service', 'Warranty Service / Honor Warranty'), ('Compensation', 'Financial Compensation for Damages'), ('Other', 'Other Remedy')], default='Refund', max_length=50)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Additional Information Required', 'Additional Information Required'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Submitted', max_length=40)),
                ('attachment', models.FileField(blank=True, help_text='Upload purchase bill, invoice, warranty, product photos or screenshots', null=True, upload_to='complaint_evidence/')),
                ('admin_response', models.TextField(blank=True, default='', help_text='Official response from Grievance Authority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consumer Complaint',
                'verbose_name_plural': 'Consumer Complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=40)),
                ('remarks', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='complaints.complaint')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
