# Generated by Django 4.2.30 on 2026-09-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_escalated',
            field=models.BooleanField(default=False, help_text='Flagged if complaint breached response SLA'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, help_text='Statutory SLA response deadline', null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Additional Information Required', 'Additional Information Required'), ('In Progress', 'In Progress'), ('Escalation Required', 'Escalation Required (SLA Breached)'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Submitted', max_length=40),
        ),
    ]
